---
- hosts: db
  become: yes
  tasks:
    - name: 'Instalaçao de Pacotes DB'
      apt:
        pkg:
          - mariadb-server
          - wget
          - zip
          - curl
          - vim
          - python3-mysqldb
        state: present
    - name: 'Download e extração DB'
      unarchive:
        src: https://github.com/rogerramossilva/devops/raw/master/db.zip
        dest: /tmp
        remote_src: yes
    - name: 'Criando DB backup'
      mysql_db:
        name: backup
        login_user: root
        login_password: ""
        state: present
    - name: 'Importação Base de Dados backup.sql'
      mysql_db:
        login_user: root
        login_password: ""
        state: import
        name: backup
        target: /tmp/backup.sql
    - name: 'Criação de Usuario Express no Mysql'
      mysql_user:
        host: '%'
        login_user: root
        login_password: ""
        name: express
        password: 'AllSafe0!'
        priv: 'backup.*:ALL'
        state: present
        column_case_sensitive: false
    - name: 'Alteração das permissoes de acesso do banco'
      replace:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '127\.0\.0\.1'
        replace: '0.0.0.0'
      notify: Restart Mysql

  handlers:
    - name: Restart Mysql
      service:
        name: mysql
        state: restarted
        enabled: yes
